# forge/core/rules.mk — top-level targets + the dependency graph. A product Makefile just `include`s
# this after config.mk sets the selection. Every buildable is one recipe run through run-recipe.sh;
# Make is the only dependency walker (host and target deps are both prerequisites).

PRODUCT_DIR ?= $(CURDIR)
BUILD       := $(PRODUCT_DIR)/build

include $(dir $(lastword $(MAKEFILE_LIST)))resolve.mk

CORE  := $(FORGE_DIR)
BUNDLE := $(BUILD)/bundles/$(CFG)

# MUST be a recipe write, not $(shell): GNU Make 3.82 exports a `define` to recipe shells but not to
# parse-time $(shell), which would write it empty. Rewritten every build so a changed selection is
# never stale; nothing keys on its mtime.
.PHONY: image toolchain hosttools print-config clean host-clean forge.conf $(BUILD)/forge.conf
$(BUILD)/forge.conf:
	@mkdir -p $(BUILD)
	@printf '%s\n' "$$FORGE_CONF_BODY" > $@
forge.conf: $(BUILD)/forge.conf
	@echo "wrote $(BUILD)/forge.conf"

# The one seed a recipe needs before it can source forge.conf (which everything else comes from).
BOOTSTRAP := PRODUCT_DIR=$(PRODUCT_DIR)

define _build_recipe   # <label> <recipe> — run one node; no per-node makefile, no dispatch on kind
@$(BOOTSTRAP) RECIPE=$(2) LAYER=$(1) $(CORE)/run-recipe.sh
endef

# --- one rule for every node --------------------------------------------------
# No per-node rule, no dispatch on kind: every buildable is a node with the SAME rule, built by
# run-recipe.sh (prereqs, then do_fetch…do_install). A node's prerequisites are ENTIRELY its recipe's
# declared deps — PKG_DEPENDS (other nodes) + PKG_HOST_DEPENDS[_<media>] (host tools) — resolved to
# node names. A recipe may write ${ROOTFS_TC}/${LIBC_TC}/${PACKAGES} there; Make expands them when the
# rule is eval'd. Every node also depends on forge.conf and on `hosttools` (which provisions `make`) —
# except `make` itself (would be a cycle).
#
# Node NAMES are one flat namespace (Bitbake-style): the four provider AXES (kernel/bootloader/libc/
# init — a stable name per axis whatever impl is selected), every host tool, every selected package,
# and the two build steps. `make <name>` builds any of them.
_NODE_HOSTPKGS := make       # the one tool every node needs; builds with system cc, carries NO deps
_AXES  := kernel bootloader libc init
_STEPS := rootfs image
_NODES := $(_AXES) $(_STEPS) $(_AGG_RECIPE_NAMES) $(PACKAGES) $(_HOST_RECIPE_NAMES)
# _noderecipe(name): the recipe behind a node. An axis resolves via virtual/* + PKG_ALIAS (resolve.mk
# already did that into *_RECIPE); anything else is found by name.
_noderecipe = $(if $(filter kernel,$(1)),$(KERNEL_RECIPE),$(if $(filter bootloader,$(1)),$(BOOTLOADER_RECIPE),$(if $(filter libc,$(1)),$(LIBC_RECIPE),$(if $(filter init,$(1)),$(INIT_RECIPE),$(call _byname,$(1))))))
# _node(name) -> the Make TARGET for a node. Providers/steps/aggregates are bare CLI verbs (`make
# kernel`, `make toolchain`); host tools and packages keep a namespace prefix so a package like
# `console` can't collide with a product Makefile's own `console:` target. _nodes maps a whole dep list
# (used at eval-time, after ${PACKAGES}/${ROOTFS_TC} have expanded).
_node  = $(if $(filter $(1),$(_AXES) $(_STEPS) $(_AGG_RECIPE_NAMES)),$(1),$(if $(filter $(1),$(_HOST_RECIPE_NAMES)),host-$(1),pkg-$(1)))
_nodes = $(foreach d,$(1),$(call _node,$(d)))

.PHONY: $(foreach n,$(_NODES),$(call _node,$(n)))
define _node_rule
$(call _node,$(1)): $(if $(filter $(1),$(_NODE_HOSTPKGS)),,hosttools) $(BUILD)/forge.conf $$(call _nodes,$$(call _vresolve,$(call _ndeps,$(call _noderecipe,$(1)))))
	$(call _build_recipe,$(1),$(call _noderecipe,$(1)))
endef
$(foreach n,$(sort $(_NODES)),$(eval $(call _node_rule,$(n))))

# hosttools = the minimal prereq every node depends on (just `make`, no cross toolchains). Its recipe
# also prints the config banner, so every build shows which toolchains the selection uses.
hosttools: $(call _node,make) $(BUILD)/forge.conf
	@printf '\n\033[1;32m[hosttools]\033[0m host build tools ready; toolchains for this selection:\n'
	@_m="$(BUILD)/hostmake/bin/make"; [ -x "$$_m" ] || _m=make; \
	 printf '  Host make  : %s  (%s)\n' \
	   "$$( "$$_m" --version 2>/dev/null | sed -n '1s/.*GNU Make //p' )" \
	   "$$( [ -x "$(BUILD)/hostmake/bin/make" ] && echo 'built locally at build/hostmake' || echo "host's own, >= 4.0" )"
	@printf '  Toolchain  : %s %s %s  [%s]  (builds everything; LIBC=%s TOOLCHAIN=%s)\n' \
	  "$(TC_ARCH)" "$(ROOTFS_TC)" "$(call _hostpkg_get,$(ROOTFS_TC),PKG_VERSION)" "$(ROOTFS_CROSS_COMPILE)" "$(LIBC)" "$(TOOLCHAIN)"

# `toolchain` (provision the common host toolchains for humans/harnesses) is no longer a rule here —
# it is an aggregate recipe (recipes-devtools/toolchain, PKG_CLASS=aggregate) built by _node_rule like
# any other node; its deps ARE its PKG_HOST_DEPENDS.

# (kernel/bootloader/libc/init, the packages, rootfs/image, and every host tool are all just nodes
# generated by _node_rule above — their edges come from each recipe's PKG_DEPENDS/PKG_HOST_DEPENDS.
# e.g. the source-toolchain 2-stage order is toolchain-gcc's own PKG_DEPENDS=libc, not a rule here.)

print-config:
	@echo "forge config:"
	@printf '  %-10s = %-8s -> %s\n' KERNEL     "$(KERNEL)"     "$(KERNEL_SRC)"
	@printf '  %-10s = %-8s -> %s\n' BOOTLOADER "$(BOOTLOADER)" "$(BOOTLDR_SRC)"
	@printf '  %-10s = %-8s -> %s (libc)\n' LIBC "$(LIBC)" "$(LIBC_SRC)"
	@printf '  %-10s = %-8s -> %s [%s]\n' TOOLCHAIN "$(TOOLCHAIN)" "$(ROOTFS_TC)" "$(ROOTFS_CROSS_COMPILE)"
	@printf '  %-10s = %s\n' PACKAGES "$(PACKAGES)"
	@echo "  BOARD=$(BOARD)  MEDIA=$(MEDIA)"
	@echo "  board targets: KERNEL_TARGET=$(KERNEL_TARGET)  ROOTFS_TARGET=$(ROOTFS_TARGET)"
	@echo "  cfg: $(CFG)"

clean: host-clean
	rm -rf $(BUILD)/bundles
	@echo "(provider build/ dirs cleaned by their own makefiles)"

.PHONY: host-clean
host-clean:
	rm -rf $(BUILD)/host $(BUILD)/toolchain-prebuilt-bootlin-glibc $(BUILD)/toolchain-prebuilt-bootlin-musl $(BUILD)/toolchain-gcc $(BUILD)/toolchain-gcc-initial $(BUILD)/hostmake $(BUILD)/hosttools $(BUILD)/pyenv \
	       $(BUILD)/toolchain $(BUILD)/toolchain-musl $(BUILD)/toolchain-bootstrap   # + legacy pre-rename dirs
	@echo "host tools removed (re-provision with 'make toolchain' or any build)"
