#!/usr/bin/env python3
"""
gen_devicetree.py — Parse a .dts file and generate devicetree.h

Emits:
  - DT_<LABEL>_<PROP> defines for each labeled node
  - DT_INST_<compat>_<N>_<PROP> defines for driver instance macros
  - DT_CHOSEN_<name> aliases
"""

import re
import sys


def parse_dts(text):
    text = re.sub(r'/\*.*?\*/', '', text, flags=re.DOTALL)
    text = re.sub(r'//.*', '', text)

    nodes = {}
    labels = {}

    def parse_node(src, path):
        props = {}
        pos = 0

        while pos < len(src):
            m = re.match(r'\s+', src[pos:])
            if m:
                pos += m.end()
                continue
            if pos >= len(src):
                break

            m = re.match(
                r'(?:(\w+)\s*:\s*)?'
                r'([\w,.-]+)'
                r'(?:@([0-9a-fA-F]+))?'
                r'\s*\{',
                src[pos:]
            )
            if m:
                label = m.group(1)
                name = m.group(2)
                addr = m.group(3)
                node_name = f"{name}@{addr}" if addr else name
                child_path = f"{path}/{node_name}" if path != "/" else f"/{node_name}"

                brace_start = pos + m.end()
                depth = 1
                i = brace_start
                while i < len(src) and depth > 0:
                    if src[i] == '{': depth += 1
                    elif src[i] == '}': depth -= 1
                    i += 1

                child_body = src[brace_start:i - 1]
                pos = i
                m2 = re.match(r'\s*;', src[pos:])
                if m2:
                    pos += m2.end()

                if label:
                    labels[label] = child_path
                parse_node(child_body, child_path)
                continue

            m = re.match(r'([\w,#.-]+)\s*=\s*', src[pos:])
            if m:
                prop_name = m.group(1)
                pos += m.end()

                m2 = re.match(r'<([^>]*)>\s*;', src[pos:])
                if m2:
                    raw = m2.group(1).strip()
                    props[prop_name] = parse_angle_value(raw)
                    pos += m2.end()
                    continue

                m2 = re.match(r'"([^"]*)"\s*;', src[pos:])
                if m2:
                    props[prop_name] = m2.group(1)
                    pos += m2.end()
                    continue

            m = re.match(r'([\w,.-]+)\s*;', src[pos:])
            if m:
                props[m.group(1)] = True
                pos += m.end()
                continue

            pos += 1

        nodes[path] = {'props': props, 'label': None}
        for lbl, lpath in labels.items():
            if lpath in nodes:
                nodes[lpath]['label'] = lbl

    def parse_angle_value(raw):
        tokens = raw.split()
        if len(tokens) == 1:
            return parse_token(tokens[0])
        return [parse_token(t) for t in tokens]

    def parse_token(t):
        if t.startswith('&'):
            return t
        if t.startswith('0x') or t.startswith('0X'):
            return int(t, 16)
        return int(t)

    m = re.search(r'/\s*\{', text)
    if not m:
        sys.exit("Error: no root node found")

    brace_start = m.end()
    depth = 1
    i = brace_start
    while i < len(text) and depth > 0:
        if text[i] == '{': depth += 1
        elif text[i] == '}': depth -= 1
        i += 1

    parse_node(text[brace_start:i - 1], "/")
    return nodes, labels


def generate_header(nodes, labels):
    lines = [
        "/* AUTO-GENERATED by gen_devicetree.py from board.dts — DO NOT EDIT */",
        "#ifndef DEVICETREE_H",
        "#define DEVICETREE_H",
        "",
    ]

    # Sysclk
    for path, node in nodes.items():
        if node['props'].get('compatible') == 'fixed-clock':
            freq = node['props'].get('clock-frequency')
            if freq:
                lines.append(f"#define DT_SYSCLK_HZ {freq}")
                lines.append("")

    # Per-label defines
    for label, path in sorted(labels.items()):
        node = nodes.get(path)
        if not node:
            continue

        prefix = f"DT_{label.upper()}"
        props = node['props']
        lines.append(f"/* {path} */")

        if 'reg' in props and isinstance(props['reg'], int):
            lines.append(f"#define {prefix}_BASE 0x{props['reg']:08X}")

        if 'clocks' in props:
            clk = props['clocks']
            if isinstance(clk, list) and len(clk) >= 3:
                lines.append(f"#define {prefix}_CLK_BUS {clk[1]}")
                lines.append(f"#define {prefix}_CLK_BIT {clk[2]}")

        skip = {'compatible', 'reg', 'clocks', 'status', 'tx-port'}
        for pname, pval in props.items():
            if pname in skip:
                continue
            cname = pname.replace('-', '_').replace(',', '_').upper()
            if isinstance(pval, int):
                lines.append(f"#define {prefix}_{cname} {pval}")
            elif isinstance(pval, str) and not pval.startswith('&'):
                lines.append(f"#define {prefix}_{cname} \"{pval}\"")

        if 'tx-port' in props:
            ref = props['tx-port']
            if isinstance(ref, str) and ref.startswith('&'):
                gpio_path = labels.get(ref[1:])
                if gpio_path and gpio_path in nodes:
                    gpio = nodes[gpio_path]
                    gpio_reg = gpio['props'].get('reg', 0)
                    lines.append(f"#define {prefix}_TX_PORT_BASE 0x{gpio_reg:08X}")
                    gpio_clk = gpio['props'].get('clocks')
                    if isinstance(gpio_clk, list) and len(gpio_clk) >= 3:
                        lines.append(f"#define {prefix}_GPIO_CLK_BIT {gpio_clk[2]}")

        lines.append("")

    # Instance defines: group nodes by compatible, assign instance numbers
    # This is what DT_INST_REG_ADDR(n) and DT_INST_PROP(n, prop) resolve to
    compat_instances = {}
    for path, node in nodes.items():
        compat = node['props'].get('compatible')
        if not compat or not isinstance(compat, str):
            continue
        if node['props'].get('status', 'okay') != 'okay':
            continue
        if compat not in compat_instances:
            compat_instances[compat] = []
        compat_instances[compat].append((path, node))

    lines.append("/* ---- Instance defines (for DT_INST macros in drivers) ---- */")
    lines.append("")

    for compat, instances in sorted(compat_instances.items()):
        compat_c = compat.replace(',', '_').replace('-', '_').upper()
        lines.append(f"/* compatible = \"{compat}\" — {len(instances)} instance(s) */")
        lines.append(f"#define DT_INST_{compat_c}_NUM_INSTANCES {len(instances)}")

        # Emit FOREACH macro: expands fn(0) fn(1) ... for each instance
        # This is what DT_INST_FOREACH_STATUS_OKAY dispatches to
        foreach_args = " ".join(f"fn({idx})" for idx in range(len(instances)))
        lines.append(f"#define DT_INST_{compat_c}_FOREACH(fn) {foreach_args}")

        for idx, (path, node) in enumerate(instances):
            prefix = f"DT_INST_{compat_c}_{idx}"
            props = node['props']

            if 'reg' in props and isinstance(props['reg'], int):
                lines.append(f"#define {prefix}_REG_ADDR 0x{props['reg']:08X}")

            if 'clocks' in props:
                clk = props['clocks']
                if isinstance(clk, list) and len(clk) >= 3:
                    lines.append(f"#define {prefix}_CLK_BUS {clk[1]}")
                    lines.append(f"#define {prefix}_CLK_BIT {clk[2]}")

            skip = {'compatible', 'reg', 'clocks', 'status', 'tx-port'}
            for pname, pval in props.items():
                if pname in skip:
                    continue
                cname = pname.replace('-', '_').replace(',', '_').upper()
                if isinstance(pval, int):
                    lines.append(f"#define {prefix}_PROP_{cname} {pval}")

            if 'tx-port' in props:
                ref = props['tx-port']
                if isinstance(ref, str) and ref.startswith('&'):
                    gpio_path = labels.get(ref[1:])
                    if gpio_path and gpio_path in nodes:
                        gpio = nodes[gpio_path]
                        gpio_reg = gpio['props'].get('reg', 0)
                        lines.append(f"#define {prefix}_PROP_TX_PORT_BASE 0x{gpio_reg:08X}")
                        gpio_clk = gpio['props'].get('clocks')
                        if isinstance(gpio_clk, list) and len(gpio_clk) >= 3:
                            lines.append(f"#define {prefix}_PROP_GPIO_CLK_BIT {gpio_clk[2]}")

            # Map label → instance for DEVICE_DT_GET
            label = node.get('label')
            if label:
                lines.append(f"#define DT_NODELABEL_{label.upper()}_INST_IDX {idx}")
                lines.append(f"#define DT_NODELABEL_{label.upper()}_COMPAT {compat_c}")
                # Reverse mapping: instance → label (for FOREACH to create named devices)
                lines.append(f"#define DT_INST_{compat_c}_{idx}_LABEL {label}")

        lines.append("")

    # Chosen
    for path, node in nodes.items():
        if path.endswith("/chosen"):
            lines.append("/* chosen aliases */")
            for pname, pval in node['props'].items():
                ref = pval if isinstance(pval, str) else (pval[0] if isinstance(pval, list) else None)
                if isinstance(ref, str) and ref.startswith('&'):
                    alias_label = ref[1:]
                    alias_prefix = f"DT_{alias_label.upper()}"
                    cname = pname.replace('-', '_').upper()
                    lines.append(f"#define DT_CHOSEN_{cname}_LABEL {alias_label.upper()}")
            lines.append("")

    lines.append("#endif")
    return "\n".join(lines) + "\n"


def main():
    if len(sys.argv) != 3:
        sys.exit(f"Usage: {sys.argv[0]} <input.dts> <output.h>")

    with open(sys.argv[1]) as f:
        text = f.read()

    nodes, labels = parse_dts(text)
    header = generate_header(nodes, labels)

    with open(sys.argv[2], 'w') as f:
        f.write(header)

    print(f"Generated {sys.argv[2]} from {sys.argv[1]} "
          f"({len(nodes)} nodes, {len(labels)} labels)")


if __name__ == '__main__':
    main()
