#!/usr/bin/env python3
"""
gen_kconfig.py — Parse Kconfig tree, resolve dependencies, generate .config

Simplified version of Linux's scripts/kconfig and Zephyr's kconfiglib.

Supports:
  - config NAME / bool "prompt" / default y|n / depends on X / help
  - menu "name" / endmenu
  - source "path"

Usage:
  python3 gen_kconfig.py Kconfig                    # apply defaults → .config
  python3 gen_kconfig.py Kconfig --set FLASH=n      # override specific options
  python3 gen_kconfig.py Kconfig --interactive       # menuconfig-like prompts
"""

import re
import sys
import os

class KconfigOption:
    def __init__(self, name):
        self.name = name
        self.prompt = ""
        self.default = "y"
        self.depends = []  # list of config names this depends on
        self.help_text = ""
        self.value = None  # None = use default after dep resolution

class KconfigParser:
    def __init__(self):
        self.options = {}  # name → KconfigOption
        self.order = []    # preserve definition order

    def parse_file(self, path):
        if not os.path.exists(path):
            return
        with open(path) as f:
            lines = f.readlines()

        current = None
        in_help = False
        i = 0
        while i < len(lines):
            line = lines[i].rstrip()
            stripped = line.strip()
            i += 1

            # Help text (indented block after "help")
            if in_help:
                if stripped and not line.startswith((' ', '\t')):
                    in_help = False
                else:
                    if current:
                        current.help_text += stripped + "\n"
                    continue

            if not stripped or stripped.startswith('#'):
                continue

            # source "path"
            m = re.match(r'source\s+"([^"]+)"', stripped)
            if m:
                self.parse_file(m.group(1))
                continue

            # config NAME
            m = re.match(r'config\s+(\w+)', stripped)
            if m:
                name = m.group(1)
                current = KconfigOption(name)
                self.options[name] = current
                self.order.append(name)
                continue

            if current:
                # bool "prompt"
                m = re.match(r'bool\s+"([^"]*)"', stripped)
                if m:
                    current.prompt = m.group(1)
                    continue

                # default y|n
                m = re.match(r'default\s+(y|n)', stripped)
                if m:
                    current.default = m.group(1)
                    continue

                # depends on X [&& Y]
                m = re.match(r'depends on\s+(.+)', stripped)
                if m:
                    deps = re.split(r'\s*&&\s*', m.group(1))
                    current.depends.extend(d.strip() for d in deps)
                    continue

                # help
                if stripped == 'help':
                    in_help = True
                    continue

            # menu / endmenu — we parse but don't use structurally
            # (a real Kconfig tool would build a menu tree)

    def resolve(self, overrides=None):
        """Resolve all options: apply defaults, check dependencies.
        Multiple passes to handle cascading (TINYFS→FS→FLASH→SPI)."""
        if overrides is None:
            overrides = {}

        # Start with defaults
        resolved = {}
        for name in self.order:
            opt = self.options[name]
            resolved[name] = overrides.get(name, opt.default)

        # Iterate until stable (deps cascade)
        for _ in range(len(self.order)):
            changed = False
            for name in self.order:
                opt = self.options[name]
                if resolved[name] != 'y':
                    continue
                for dep in opt.depends:
                    if resolved.get(dep, 'n') != 'y':
                        resolved[name] = 'n'
                        changed = True
                        break
            if not changed:
                break

        return resolved

    def write_config(self, resolved, path):
        with open(path, 'w') as f:
            f.write("# Generated by gen_kconfig.py from Kconfig\n")
            for name in self.order:
                val = resolved[name]
                opt = self.options[name]
                if opt.prompt:
                    f.write(f"# {opt.prompt}\n")
                f.write(f"CONFIG_{name}={val}\n")
        enabled = sum(1 for v in resolved.values() if v == 'y')
        print(f"Generated {path}: {enabled}/{len(resolved)} options enabled")

    def interactive(self, resolved):
        """Simple interactive config (like make oldconfig)."""
        print("=== Configuration ===")
        print("Press Enter for default, y/n to change\n")
        for name in self.order:
            opt = self.options[name]
            current = resolved[name]

            # Check if deps are met
            deps_met = True
            for dep in opt.depends:
                if resolved.get(dep, 'n') != 'y':
                    deps_met = False
                    break

            if not deps_met:
                resolved[name] = 'n'
                print(f"  CONFIG_{name}: n (dependency not met: {', '.join(opt.depends)})")
                continue

            prompt = opt.prompt or name
            choice = input(f"  {prompt} (CONFIG_{name}) [{current}]: ").strip()
            if choice in ('y', 'n'):
                resolved[name] = choice
            # else keep current

        return resolved


def main():
    if len(sys.argv) < 2:
        sys.exit(f"Usage: {sys.argv[0]} <Kconfig> [--set X=y] [--interactive]")

    kconfig_path = sys.argv[1]
    overrides = {}
    interactive = False

    i = 2
    while i < len(sys.argv):
        if sys.argv[i] == '--set' and i + 1 < len(sys.argv):
            key, val = sys.argv[i + 1].split('=', 1)
            overrides[key] = val
            i += 2
        elif sys.argv[i] == '--interactive':
            interactive = True
            i += 1
        else:
            i += 1

    parser = KconfigParser()
    parser.parse_file(kconfig_path)
    resolved = parser.resolve(overrides)

    if interactive:
        resolved = parser.interactive(resolved)

    parser.write_config(resolved, '.config')


if __name__ == '__main__':
    main()
