#!/usr/bin/env python3
"""Generate a STARTER kart model as data: src/assets/kart/kart.obj (+ kart.mtl) AND a separate
src/assets/kart/wheel.obj (+ wheel.mtl) — one FRONT wheel centred at the origin so the engine can
draw it with an extra steering yaw (front wheels turn instead of the body leaning like a motorbike).
The body keeps its REAR wheels; the two front wheels are drawn separately by the game.
Plain Wavefront OBJ, so you can hand-edit or replace with a Blender export later.
Run: python3 tools/gen_kart_obj.py"""
import os, math
OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "src", "assets", "kart")
os.makedirs(OUT, exist_ok=True)
verts=[]; faces=[]   # faces: list of ("mtl", [idx,...])  1-based

def box(lo, hi, mtl):
    (x0,y0,z0),(x1,y1,z1)=lo,hi
    cs=[(x0,y0,z0),(x1,y0,z0),(x1,y1,z0),(x0,y1,z0),(x0,y0,z1),(x1,y0,z1),(x1,y1,z1),(x0,y1,z1)]
    b=len(verts); verts.extend(cs)
    for q in [(1,2,3,4),(6,5,8,7),(5,6,2,1),(4,3,7,8),(2,6,7,3),(5,1,4,8)]:
        faces.append((mtl,[b+i for i in q]))

def sph(c, r, subdiv, mtl):
    rings, segs = 4*subdiv, 8*subdiv; grid=[]
    for i in range(rings+1):
        th=math.pi*i/rings; row=[]
        for j in range(segs+1):
            ph=2*math.pi*j/segs
            verts.append((c[0]+r*math.sin(th)*math.cos(ph), c[1]+r*math.cos(th), c[2]+r*math.sin(th)*math.sin(ph)))
            row.append(len(verts))
        grid.append(row)
    for i in range(rings):
        for j in range(segs):
            faces.append((mtl,[grid[i][j],grid[i][j+1],grid[i+1][j+1],grid[i+1][j]]))

def cyl(c, r, w, segs, mtl):
    cx,cy,cz=c; R=[]; L=[]
    for i in range(segs+1):
        a=2*math.pi*i/segs; y=cy+r*math.cos(a); z=cz+r*math.sin(a)
        verts.append((cx+w,y,z)); R.append(len(verts))
        verts.append((cx-w,y,z)); L.append(len(verts))
    verts.append((cx+w,cy,cz)); cR=len(verts)
    verts.append((cx-w,cy,cz)); cL=len(verts)
    for i in range(segs):
        faces.append((mtl,[R[i],R[i+1],L[i+1],L[i]]))
        faces.append((mtl,[cR,R[i+1],R[i]]))
        faces.append((mtl,[cL,L[i],L[i+1]]))

def write_obj(objname, mtls):
    with open(os.path.join(OUT,objname+".mtl"),"w") as f:
        f.write("# Turbo Kart material library (generated)\n")
        for name,kd in mtls:
            f.write(f"newmtl {name}\nKd {kd[0]} {kd[1]} {kd[2]}\nmap_Kd kart_tex.png\n")   # detail texture x material colour
    with open(os.path.join(OUT,objname+".obj"),"w") as f:
        f.write("# Turbo Kart model (generated by tools/gen_kart_obj.py; edit or replace freely)\n")
        f.write(f"mtllib {objname}.mtl\n")
        for v in verts: f.write("v %.4f %.4f %.4f\n" % v)
        uvs=[]; fout=[]                                                    # give every face a full-texture panel UV
        for mtl,idx in faces:
            n=len(idx); b=len(uvs)
            canon=[(0,0),(1,0),(1,1),(0,1)] if n==4 else ([(0,0),(1,0),(0.5,1)] if n==3 else [(0,0)]*n)
            uvs+=canon; fout.append((mtl,[(idx[k],b+1+k) for k in range(n)]))
        for uv in uvs: f.write("vt %.3f %.3f\n"%uv)
        cur=None
        for mtl,ft in fout:
            if mtl!=cur: f.write(f"usemtl {mtl}\n"); cur=mtl
            f.write("f "+" ".join("%d/%d"%(v,t) for v,t in ft)+"\n")
    print("wrote assets/kart/%s.obj  (%d verts, %d faces) + %s.mtl" % (objname, len(verts), len(faces), objname))

BODY_MTLS=[("tint_body",(1.0,1.0,1.0)),("wheel",(0.11,0.11,0.125)),("seat",(0.20,0.20,0.23)),
           ("chassis",(0.14,0.14,0.16)),("accent",(0.93,0.93,0.96)),("chrome",(0.72,0.74,0.80))]

# --- the kart BODY (nose = +Z; wheels touch y=0). FRONT wheels are a separate mesh (steerable). ---
box((-0.64,0.24,-1.18),(0.64,0.50, 1.18),"chassis")    # dark base frame
box((-0.56,0.48,-0.72),(0.56,0.74, 0.60),"tint_body")  # cowl (character colour)
box((-0.46,0.48, 0.55),(0.46,0.72, 1.08),"tint_body")  # hood
box((-0.12,0.72, 0.50),(0.12,0.75, 1.15),"accent")     # white nose stripe
box((-0.52,0.30, 1.06),(0.52,0.48, 1.22),"chrome")     # front bumper
box(( 0.50,0.32,-0.35),(0.66,0.58, 0.55),"tint_body")  # right side pod
box((-0.66,0.32,-0.35),(-0.50,0.58,0.55),"tint_body")  # left side pod
box((-0.28,0.74,-0.02),(0.28,1.00, 0.16),"chassis")    # windscreen
box((-0.30,0.56,-0.58),(0.30,1.02, 0.04),"seat")       # driver torso
sph((0.0,1.20,-0.28),0.28,1,"tint_body")               # helmet
box((-0.58,0.78,-1.18),(0.58,0.98,-1.02),"chassis")    # rear wing
box((-0.50,0.50,-1.14),(-0.40,0.80,-1.06),"chrome")    # wing upright L
box(( 0.40,0.50,-1.14),( 0.50,0.80,-1.06),"chrome")    # wing upright R
cyl(( 0.76,0.38,-0.84),0.40,0.18,8,"wheel")            # rear-right (bigger)
cyl((-0.76,0.38,-0.84),0.40,0.18,8,"wheel")            # rear-left
write_obj("kart", BODY_MTLS)

# --- one FRONT wheel, centred at the origin (axle along X) so the game can place + steer it ---
verts=[]; faces=[]
cyl((0.0,0.0,0.0),0.34,0.15,10,"wheel")
write_obj("wheel", [("wheel",(0.11,0.11,0.125))])
