obj-$(CONFIG_CPU_CORTEX_M4)     += startup.o
obj-$(CONFIG_CPU_CORTEX_M0PLUS) += startup_m0plus.o
obj-$(CONFIG_SYSTICK)           += systick.o
obj-$(CONFIG_SYSTICK)           += systick_m0plus.o
obj-$(CONFIG_SMP)               += smp_rp2040.o
