# STM32 drivers
obj-$(CONFIG_CLOCK_STM32)  += clock_stm32.o
obj-$(CONFIG_UART_STM32)   += uart_stm32.o
obj-$(CONFIG_GPIO_STM32)   += gpio_stm32.o
obj-$(CONFIG_SPI_STM32)    += spi_stm32.o
obj-$(CONFIG_FLASH)        += flash_w25q.o
obj-$(CONFIG_GPIO_KEYS)    += gpio_keys.o
obj-$(CONFIG_GPIO_LEDS)    += gpio_leds.o
obj-$(CONFIG_DISPLAY_ILI9341) += display_ili9341.o
obj-$(CONFIG_I2S_STM32)    += i2s_stm32.o
obj-$(CONFIG_ADC_STM32)    += adc_stm32.o
obj-$(CONFIG_INPUT_EXTI)   += input_exti.o

# RP2040 drivers
obj-$(CONFIG_CLOCK_RP2040) += clock_rp2040.o
obj-$(CONFIG_UART_PL011)   += uart_pl011.o
obj-$(CONFIG_GPIO_RP2040)  += gpio_rp2040.o

# IPC drivers
obj-$(CONFIG_IPC_STM32H745) += ipc_stm32h745.o

# Ethernet drivers
obj-$(CONFIG_ETH_ENC28J60) += eth_enc28j60.o
