obj-$(CONFIG_CLOCK)     += clock.o
obj-$(CONFIG_UART)      += uart.o
obj-$(CONFIG_GPIO)      += gpio.o
obj-$(CONFIG_SPI)       += spi.o
obj-$(CONFIG_FLASH)     += flash.o
obj-$(CONFIG_GPIO_KEYS) += gpio_keys.o
obj-$(CONFIG_GPIO_LEDS) += gpio_leds.o
