# STM32 drivers (only compiled when their CONFIG is set)
obj-$(CONFIG_CLOCK_STM32)  += clock.o
obj-$(CONFIG_UART_STM32)   += uart.o
obj-$(CONFIG_GPIO_STM32)   += gpio.o
obj-$(CONFIG_SPI_STM32)    += spi.o
obj-$(CONFIG_FLASH)        += flash.o
obj-$(CONFIG_GPIO_KEYS)    += gpio_keys.o
obj-$(CONFIG_GPIO_LEDS)    += gpio_leds.o

# RP2040 drivers
obj-$(CONFIG_CLOCK_RP2040) += clock_rp2040.o
obj-$(CONFIG_UART_PL011)   += uart_pl011.o
obj-$(CONFIG_GPIO_RP2040)  += gpio_rp2040.o
