// expect: 42
// >64 struct tags used to overflow the tag table silently, splitting a forward declaration from
// its later definition so 'ptr->member' saw an empty (opaque) struct. Declare many tags, then
// forward-declare a struct, take a pointer, define it later, and access a member through the pointer.
struct pad00 { int a; };
struct pad01 { int a; };
struct pad02 { int a; };
struct pad03 { int a; };
struct pad04 { int a; };
struct pad05 { int a; };
struct pad06 { int a; };
struct pad07 { int a; };
struct pad08 { int a; };
struct pad09 { int a; };
struct pad10 { int a; };
struct pad11 { int a; };
struct pad12 { int a; };
struct pad13 { int a; };
struct pad14 { int a; };
struct pad15 { int a; };
struct pad16 { int a; };
struct pad17 { int a; };
struct pad18 { int a; };
struct pad19 { int a; };
struct pad20 { int a; };
struct pad21 { int a; };
struct pad22 { int a; };
struct pad23 { int a; };
struct pad24 { int a; };
struct pad25 { int a; };
struct pad26 { int a; };
struct pad27 { int a; };
struct pad28 { int a; };
struct pad29 { int a; };
struct pad30 { int a; };
struct pad31 { int a; };
struct pad32 { int a; };
struct pad33 { int a; };
struct pad34 { int a; };
struct pad35 { int a; };
struct pad36 { int a; };
struct pad37 { int a; };
struct pad38 { int a; };
struct pad39 { int a; };
struct pad40 { int a; };
struct pad41 { int a; };
struct pad42 { int a; };
struct pad43 { int a; };
struct pad44 { int a; };
struct pad45 { int a; };
struct pad46 { int a; };
struct pad47 { int a; };
struct pad48 { int a; };
struct pad49 { int a; };
struct pad50 { int a; };
struct pad51 { int a; };
struct pad52 { int a; };
struct pad53 { int a; };
struct pad54 { int a; };
struct pad55 { int a; };
struct pad56 { int a; };
struct pad57 { int a; };
struct pad58 { int a; };
struct pad59 { int a; };
struct pad60 { int a; };
struct pad61 { int a; };
struct pad62 { int a; };
struct pad63 { int a; };
struct pad64 { int a; };
struct pad65 { int a; };
struct pad66 { int a; };
struct pad67 { int a; };
struct pad68 { int a; };
struct pad69 { int a; };
struct pad70 { int a; };
struct pad71 { int a; };
struct pad72 { int a; };
struct pad73 { int a; };
struct pad74 { int a; };
struct pad75 { int a; };
struct pad76 { int a; };
struct pad77 { int a; };
struct pad78 { int a; };
struct pad79 { int a; };
struct late;
struct late *lp;
struct late { int flags; int extra; };
static struct late L = { 42, 7 };
int main(void) { lp = &L; return lp->flags; }
