#!/usr/bin/env python3
"""
convert_tiles.py — Convert sprite PNGs to binary assets for the PPU

Reads PNG files from this directory and produces:
  tiles.bin      — RGB565 pixel data (uploaded to FPGA SPRAM)
  tile_table.bin — 4 bytes per tile: base_addr_hi, base_addr_lo, width, height
  tiles.h        — C header with tile indices and dimensions

PNG transparent pixels (alpha=0) become 0xF81F (PPU transparent marker).

To regenerate the source PNGs, run generate_sprites.py first.
"""
import struct
from PIL import Image

def rgb_to_565(r, g, b):
    return ((r >> 3) << 11) | ((g >> 2) << 5) | (b >> 3)

import math

TRANSPARENT = 0xF81F

# Tile manifest: (name, filename, target_index_or_None)
# Order matters — tiles are packed sequentially.
# Use target_index to skip slots (padded with 1x1 transparent tiles).
MANIFEST = [
    ("PLAYER",   "player.png",   None),
    ("OBS_0",    "obs_0.png",    None),
    ("OBS_1",    "obs_1.png",    None),
    ("OBS_2",    "obs_2.png",    None),
    ("GROUND",   "ground.png",   None),
    ("DIGIT_0",  "digit_0.png",  10),
    ("DIGIT_1",  "digit_1.png",  None),
    ("DIGIT_2",  "digit_2.png",  None),
    ("DIGIT_3",  "digit_3.png",  None),
    ("DIGIT_4",  "digit_4.png",  None),
    ("DIGIT_5",  "digit_5.png",  None),
    ("DIGIT_6",  "digit_6.png",  None),
    ("DIGIT_7",  "digit_7.png",  None),
    ("DIGIT_8",  "digit_8.png",  None),
    ("DIGIT_9",  "digit_9.png",  None),
    ("TITLE",    "title.png",    20),
    ("GAMEOVER", "gameover.png",  None),
]

tiles = []   # flat list of RGB565 pixels
table = []   # (byte_addr, width, height) per slot
tile_names = {}  # name → index

def pad_to(idx):
    """Pad with 1x1 transparent tiles up to target index."""
    while len(table) < idx:
        addr = len(tiles) * 2
        table.append((addr, 1, 1))
        tiles.append(TRANSPARENT)

def load_png(filename):
    """Load a PNG, pad width to power of 2, return (padded_width, height, [rgb565 pixels])."""
    img = Image.open(filename).convert('RGBA')
    w, h = img.width, img.height
    # Pad width to next power of 2
    padded_w = 1
    while padded_w < w:
        padded_w <<= 1
    pixels = []
    for y in range(h):
        for x in range(padded_w):
            if x < w:
                r, g, b, a = img.getpixel((x, y))
                if a < 128:
                    pixels.append(TRANSPARENT)
                else:
                    pixels.append(rgb_to_565(r, g, b))
            else:
                pixels.append(TRANSPARENT)  # padding
    return padded_w, h, pixels

# --- Process manifest ---
for name, filename, target_idx in MANIFEST:
    if target_idx is not None:
        pad_to(target_idx)
    tile_names[name] = len(table)
    w, h, pixels = load_png(filename)
    addr = len(tiles) * 2
    table.append((addr, w, h))
    tiles.extend(pixels)

# --- Procedural tiles (no PNG) ---
# GROUND_FILL: a solid 16x40 ground band used to fill from the ground line to the
# bottom of the screen (the PNG GROUND tile is only 4px tall = a thin line). 40 is
# the PPU's max sprite height (pixel_gen scan window). Color = the ground brown.
GROUND_FILL_COLOR = 0x1B23
gf_w, gf_h = 16, 40
tile_names["GROUND_FILL"] = len(table)
table.append((len(tiles) * 2, gf_w, gf_h))
tiles.extend([GROUND_FILL_COLOR] * (gf_w * gf_h))

# --- Write tiles.bin ---
with open('tiles.bin', 'wb') as f:
    for px in tiles:
        f.write(struct.pack('<H', px))

# --- Write tile_table.bin (format: base_hi, base_lo, width_shift, height) ---
with open('tile_table.bin', 'wb') as f:
    for addr, w, h in table:
        # Width must be power of 2 for shift-based addressing
        assert w > 0 and (w & (w - 1)) == 0, f"Tile width {w} must be power of 2"
        width_shift = int(math.log2(w))
        f.write(struct.pack('BBBB', (addr >> 8) & 0xFF, addr & 0xFF, width_shift & 0xFF, h & 0xFF))

# --- Write tiles.h ---
with open('tiles.h', 'w') as f:
    f.write("/* Auto-generated by convert_tiles.py — do not edit */\n")
    f.write("#ifndef TILES_H\n#define TILES_H\n\n")
    f.write("/* Tile indices */\n")
    for name, idx in tile_names.items():
        f.write(f"#define TILE_{name:<12s} {idx}\n")
    f.write(f"\n#define TILE_COUNT       {len(table)}\n")
    f.write("\n/* Tile dimensions (pixels) */\n")
    for name, idx in tile_names.items():
        _, w, h = table[idx]
        f.write(f"#define TILE_{name}_W     {w}\n")
        f.write(f"#define TILE_{name}_H     {h}\n")
    f.write("\n#endif\n")

print(f"tiles.bin: {len(tiles)*2} bytes ({len(table)} tiles)")
print(f"tile_table.bin: {len(table)*4} bytes")
print(f"tiles.h: {len(tile_names)} tiles defined")
