/* Auto-generated by convert_tiles.py — do not edit */
#ifndef TILES_H
#define TILES_H

/* Tile indices */
#define TILE_PLAYER       0
#define TILE_OBS_0        1
#define TILE_OBS_1        2
#define TILE_OBS_2        3
#define TILE_GROUND       4
#define TILE_DIGIT_0      10
#define TILE_DIGIT_1      11
#define TILE_DIGIT_2      12
#define TILE_DIGIT_3      13
#define TILE_DIGIT_4      14
#define TILE_DIGIT_5      15
#define TILE_DIGIT_6      16
#define TILE_DIGIT_7      17
#define TILE_DIGIT_8      18
#define TILE_DIGIT_9      19
#define TILE_TITLE        20
#define TILE_GAMEOVER     21
#define TILE_GROUND_FILL  22   /* solid 16x40 ground band (appended, non-PNG) */

#define TILE_COUNT       23

/* Tile dimensions (pixels) */
#define TILE_PLAYER_W     16
#define TILE_PLAYER_H     20
#define TILE_OBS_0_W     16
#define TILE_OBS_0_H     20
#define TILE_OBS_1_W     16
#define TILE_OBS_1_H     25
#define TILE_OBS_2_W     16
#define TILE_OBS_2_H     30
#define TILE_GROUND_W     16
#define TILE_GROUND_H     4
#define TILE_DIGIT_0_W     8
#define TILE_DIGIT_0_H     10
#define TILE_DIGIT_1_W     8
#define TILE_DIGIT_1_H     10
#define TILE_DIGIT_2_W     8
#define TILE_DIGIT_2_H     10
#define TILE_DIGIT_3_W     8
#define TILE_DIGIT_3_H     10
#define TILE_DIGIT_4_W     8
#define TILE_DIGIT_4_H     10
#define TILE_DIGIT_5_W     8
#define TILE_DIGIT_5_H     10
#define TILE_DIGIT_6_W     8
#define TILE_DIGIT_6_H     10
#define TILE_DIGIT_7_W     8
#define TILE_DIGIT_7_H     10
#define TILE_DIGIT_8_W     8
#define TILE_DIGIT_8_H     10
#define TILE_DIGIT_9_W     8
#define TILE_DIGIT_9_H     10
#define TILE_TITLE_W     64
#define TILE_TITLE_H     14
#define TILE_GAMEOVER_W     128
#define TILE_GAMEOVER_H     14
#define TILE_GROUND_FILL_W  16
#define TILE_GROUND_FILL_H  40

#endif
